### ISSUE TITLE
LuceneRDD does not handle null/missed values 

### ISSUE THREAD

**Issue by dserdyuk** [zouzias/spark-lucenerdd#47]

**Comment by dserdyuk** [comment]
Caused by: scala.MatchError: null
  at org.zouzias.spark.lucenerdd.package$.typeToDocument(package.scala:65)
  at org.zouzias.spark.lucenerdd.package$$anonfun$sparkRowToDocument$1.apply(package.scala:123)
  at org.zouzias.spark.lucenerdd.package$$anonfun$sparkRowToDocument$1.apply(package.scala:121)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
  at org.zouzias.spark.lucenerdd.package$.sparkRowToDocument(package.scala:121)
  at org.zouzias.spark.lucenerdd.LuceneRDD$$anonfun$apply$5.apply(LuceneRDD.scala:316)
  at org.zouzias.spark.lucenerdd.LuceneRDD$$anonfun$apply$5.apply(LuceneRDD.scala:316)
  at org.zouzias.spark.lucenerdd.partition.LuceneRDDPartition$$anonfun$3.apply(LuceneRDDPartition.scala:47)
  at org.zouzias.spark.lucenerdd.partition.LuceneRDDPartition$$anonfun$3.apply(LuceneRDDPartition.scala:45)
  at scala.collection.Iterator$class.foreach(Iterator.scala:742)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
  at org.zouzias.spark.lucenerdd.partition.LuceneRDDPartition.<init>(LuceneRDDPartition.scala:45)
  at org.zouzias.spark.lucenerdd.partition.LuceneRDDPartition$.apply(LuceneRDDPartition.scala:136)
  at org.zouzias.spark.lucenerdd.LuceneRDD$$anonfun$7.apply(LuceneRDD.scala:289)

**Comment by dserdyuk** [comment]
CC @zouzias

**Comment by zouzias** [comment]
Hey I will look at it asap.

Quick question: do you instantiate the LuceneRDD with a DataFrame??

**Comment by dserdyuk** [comment]
No from rdd.
I manage to get it work like this : 
```
 val lrdd =  LuceneRDD(df.select(df("nullColumne")).map{ case  v  => if (v.getString(0) == null) "null" else v.getString(0) })

```

**Comment by dserdyuk** [comment]
btw, can save LuceneRDD using DataSource Api for example in parquet ?

**Comment by dserdyuk** [comment]
it would be also useful have ability to index only particular columns( add some param to LuceneRDD)

**Comment by zouzias** [comment]
"it would be also useful have ability to index only particular columns( add some param to LuceneRDD)"

For now, this can be done by 

```
val luceneRDD = LuceneRDD(dataframe.select("columnA", "columnB"))
```

**Comment by zouzias** [comment]
The `LuceneRDD` API so far collects the results to the driver. I think that it is a good idea that LuceneRDD returns an `RDD[LuceneRDDResult]` instead of a `List[X]`. WDYT?

If you want to save them to parquet, you can do (with some extra imports)

```
val results = lucene.termQuert(xxx)
sc.parallelize(results).toDF
```

**Comment by zouzias** [comment]
Hi Denis, I have a PR that fixes the null/missing value issue (feel free to take a look). If it passes the tests, I will release this into the next version today.

**Comment by dserdyuk** [comment]
Sorry, I read it wrong for the first time. I meant saving  indexed documents itself when I say about saving to parquet. So it can be reused and prevent reading/reindexing original data from scratch. It's good use case when you keep ingesting the new data to your warehouse, transform it to Hive table, add indexes and use it for further requests. Thus I'm not interesting in saving result but in index itself.
 
Yes, it's good idea to return RDD or DataFrame  of results rather than collecting result for sure.

**Comment by zouzias** [comment]
Fo such a case study that you want your index to be persistent, it is advisable to use

https://github.com/elastic/elasticsearch-hadoop

for elasticsearch and 

https://github.com/lucidworks/spark-solr

for Apache Solr(Cloud). Using these connectors, you can interact with an elasticsearch or a Solr cluster/server. The purpose of this library is provide immutable RDDs with Lucene functionality.
