### ISSUE TITLE
Error when creating LuceneRDD in spark lucene rdd

### ISSUE THREAD

**Issue by SwathiTallapalli** [zouzias/spark-lucenerdd#90]
hi
I am trying to use Record Linkage in LuceneRDD in spark1.6.1 using https://github.com/zouzias/spark-lucenerdd/tree/branch_spark_1.x
I followed all the steps mentioned in the article.
When I do val luceneRDD = LuceneRDD(countries) I am getting the below error.
error: No implicit view available from String => org.apache.lucene.document.Document
any help is highly appreciated
LuceneRDD(countries) 
^
Any help me to solve this issue is appreciated
Thanks in advance

**Comment by zouzias** [comment]
Hi there,

You need to import the implicits from String => Document,

```
import org.zouzias.spark.lucenerdd._
```

See also, my answer here: https://github.com/zouzias/spark-lucenerdd/issues/85

Let me know if it works.

**Comment by SwathiTallapalli** [comment]
Yes this error has fixed.

When I say

linked.take(4).foreach(println) It is giving an exception.

Can u please help me, I am completely new to spark and scala.



(0 + 1) / 2]17/01/25 09:13:13 WARN scheduler.TaskSetManager: Lost task
0.0 in stage 7.0 (TID 15, quickstart.cloudera):
java.lang.NoSuchMethodError:
org.apache.lucene.codecs.compressing.CompressingStoredFieldsFormat.<init>(Ljava/lang/String;Lorg/apache/lucene/codecs/compressing/CompressionMode;I)V
	at org.apache.lucene.codecs.lucene41.Lucene41Codec$1.<init>(Lucene41Codec.java:59)
	at org.apache.lucene.codecs.lucene41.Lucene41Codec.<init>(Lucene41Codec.java:59)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:374)
	at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:72)
	at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:49)
	at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:38)
	at org.apache.lucene.codecs.Codec$Holder.<clinit>(Codec.java:47)
	at org.apache.lucene.codecs.Codec.getDefault(Codec.java:140)
	at org.apache.lucene.index.LiveIndexWriterConfig.<init>(LiveIndexWriterConfig.java:120)
	at org.apache.lucene.index.IndexWriterConfig.<init>(IndexWriterConfig.java:140)
	at org.zouzias.spark.lucenerdd.store.IndexWithTaxonomyWriter$class.indexWriter(IndexWithTaxonomyWriter.scala:31)
	at org.zouzias.spark.lucenerdd.partition.LuceneRDDPartition.indexWriter$lzycompute(LuceneRDDPartition.scala:34)
	at org.zouzias.spark.lucenerdd.partition.LuceneRDDPartition.indexWriter(LuceneRDDPartition.scala:34)
	at org.zouzias.spark.lucenerdd.partition.LuceneRDDPartition$$anonfun$3.apply(LuceneRDDPartition.scala:51)
	at org.zouzias.spark.lucenerdd.partition.LuceneRDDPartition$$anonfun$3.apply(LuceneRDDPartition.scala:48)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at org.zouzias.spark.lucenerdd.partition.LuceneRDDPartition.<init>(LuceneRDDPartition.scala:48)
	at org.zouzias.spark.lucenerdd.partition.LuceneRDDPartition$.apply(LuceneRDDPartition.scala:155)
	at org.zouzias.spark.lucenerdd.LuceneRDD$$anonfun$6.apply(LuceneRDD.scala:286)
	at org.zouzias.spark.lucenerdd.LuceneRDD$$anonfun$6.apply(LuceneRDD.scala:286)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

17/01/25 09:13:14 ERROR cluster.YarnScheduler: Lost executor 1 on
quickstart.cloudera: Container marked as failed:
container_1485279684410_0003_02_000002 on host: quickstart.cloudera.
Exit status: 50. Diagnostics: Exception from container-launch.
Container id: container_1485279684410_0003_02_000002
Exit code: 50
Stack trace: ExitCodeException exitCode=50:
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:578)
	at org.apache.hadoop.util.Shell.run(Shell.java:481)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:763)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:213)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)


Container exited with a non-zero exit code 50

17/01/25 09:13:14 WARN scheduler.TaskSetManager: Lost task 1.0 in
stage 7.0 (TID 16, quickstart.cloudera): ExecutorLostFailure (executor
1 exited caused by one of the running tasks) Reason: Container marked
as failed: container_1485279684410_0003_02_000002 on host:
quickstart.cloudera. Exit status: 50. Diagnostics: Exception from
container-launch.
Container id: container_1485279684410_0003_02_000002
Exit code: 50
Stack trace: ExitCodeException exitCode=50:
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:578)
	at org.apache.hadoop.util.Shell.run(Shell.java:481)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:763)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:213)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)


Container exited with a non-zero exit code 50

17/01/25 09:13:14 WARN spark.ExecutorAllocationManager: Attempted to
mark unknown executor 1 idle
17/01/25 09:13:14 ERROR scheduler.LiveListenerBus: Listener
SQLListener threw an exception
java.lang.NullPointerException
	at org.apache.spark.sql.execution.ui.SQLListener.onTaskEnd(SQLListener.scala:167)
	at org.apache.spark.scheduler.SparkListenerBus$class.onPostEvent(SparkListenerBus.scala:42)
	at org.apache.spark.scheduler.LiveListenerBus.onPostEvent(LiveListenerBus.scala:31)
	at org.apache.spark.scheduler.LiveListenerBus.onPostEvent(LiveListenerBus.scala:31)
	at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:55)
	at org.apache.spark.util.AsynchronousListenerBus.postToAll(AsynchronousListenerBus.scala:37)
	at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(AsynchronousListenerBus.scala:80)
	at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(AsynchronousListenerBus.scala:65)
	at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(AsynchronousListenerBus.scala:65)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
	at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1.apply$mcV$sp(AsynchronousListenerBus.scala:64)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1181)
	at org.apache.spark.util.AsynchronousListenerBus$$anon$1.run(AsynchronousListenerBus.scala:63)
17/01/25 09:13:14 WARN
cluster.YarnSchedulerBackend$YarnSchedulerEndpoint: Container marked
as failed: container_1485279684410_0003_02_000002 on host:
quickstart.cloudera. Exit status: 50. Diagnostics: Exception from
container-launch.
Container id: container_1485279684410_0003_02_000002
Exit code: 50
Stack trace: ExitCodeException exitCode=50:
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:578)
	at org.apache.hadoop.util.Shell.run(Shell.java:481)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:763)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:213)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)


Container exited with a non-zero exit code 50

[Stage 7:>                                                          (0
+ 1) / 2]17/01/25 09:13:22 ERROR cluster.YarnScheduler: Lost executor
2 on quickstart.cloudera: Container marked as failed:
container_1485279684410_0003_02_000003 on host: quickstart.cloudera.
Exit status: 50. Diagnostics: Exception from container-launch.
Container id: container_1485279684410_0003_02_000003
Exit code: 50
Stack trace: ExitCodeException exitCode=50:
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:578)
	at org.apache.hadoop.util.Shell.run(Shell.java:481)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:763)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:213)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)


Container exited with a non-zero exit code 50

17/01/25 09:13:22 WARN scheduler.TaskSetManager: Lost task 0.1 in
stage 7.0 (TID 18, quickstart.cloudera): ExecutorLostFailure (executor
2 exited caused by one of the running tasks) Reason: Container marked
as failed: container_1485279684410_0003_02_000003 on host:
quickstart.cloudera. Exit status: 50. Diagnostics: Exception from
container-launch.
Container id: container_1485279684410_0003_02_000003
Exit code: 50
Stack trace: ExitCodeException exitCode=50:
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:578)
	at org.apache.hadoop.util.Shell.run(Shell.java:481)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:763)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:213)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)


Container exited with a non-zero exit code 50

17/01/25 09:13:22 WARN
cluster.YarnSchedulerBackend$YarnSchedulerEndpoint: Container marked
as failed: container_1485279684410_0003_02_000003 on host:
quickstart.cloudera. Exit status: 50. Diagnostics: Exception from
container-launch.
Container id: container_1485279684410_0003_02_000003
Exit code: 50
Stack trace: ExitCodeException exitCode=50:
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:578)
	at org.apache.hadoop.util.Shell.run(Shell.java:481)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:763)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:213)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)


Container exited with a non-zero exit code 50

17/01/25 09:13:22 WARN spark.ExecutorAllocationManager: Attempted to
mark unknown executor 2 idle
17/01/25 09:13:22 ERROR scheduler.LiveListenerBus: Listener
SQLListener threw an exception
java.lang.NullPointerException
	at org.apache.spark.sql.execution.ui.SQLListener.onTaskEnd(SQLListener.scala:167)
	at org.apache.spark.scheduler.SparkListenerBus$class.onPostEvent(SparkListenerBus.scala:42)
	at org.apache.spark.scheduler.LiveListenerBus.onPostEvent(LiveListenerBus.scala:31)
	at org.apache.spark.scheduler.LiveListenerBus.onPostEvent(LiveListenerBus.scala:31)
	at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:55)
	at org.apache.spark.util.AsynchronousListenerBus.postToAll(AsynchronousListenerBus.scala:37)
	at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(AsynchronousListenerBus.scala:80)
	at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(AsynchronousListenerBus.scala:65)
	at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(AsynchronousListenerBus.scala:65)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
	at org.apache.spark.util.AsynchronousListenerBus$$anon$1$$anonfun$run$1.apply$mcV$sp(AsynchronousListenerBus.scala:64)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1181)
	at org.apache.spark.util.AsynchronousListenerBus$$anon$1.run(AsynchronousListenerBus.scala:63)
[Stage 7:>                                                          (0
+ 1) / 2]17/01/25 09:13:30 WARN scheduler.TaskSetManager: Lost task
0.2 in stage 7.0 (TID 19, quickstart.cloudera):
java.lang.NoSuchMethodError:
org.apache.lucene.codecs.compressing.CompressingStoredFieldsFormat.<init>(Ljava/lang/String;Lorg/apache/lucene/codecs/compressing/CompressionMode;I)V
	at org.apache.lucene.codecs.lucene41.Lucene41Codec$1.<init>(Lucene41Codec.java:59)
	at org.apache.lucene.codecs.lucene41.Lucene41Codec.<init>(Lucene41Codec.java:59)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:374)
	at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:72)
	at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:49)
	at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:38)
	at org.apache.lucene.codecs.Codec$Holder.<clinit>(Codec.java:47)
	at org.apache.lucene.codecs.Codec.getDefault(Codec.java:140)
	at org.apache.lucene.index.LiveIndexWriterConfig.<init>(LiveIndexWriterConfig.java:120)
	at org.apache.lucene.index.IndexWriterConfig.<init>(IndexWriterConfig.java:140)
	at org.zouzias.spark.lucenerdd.store.IndexWithTaxonomyWriter$class.indexWriter(IndexWithTaxonomyWriter.scala:31)
	at org.zouzias.spark.lucenerdd.partition.LuceneRDDPartition.indexWriter$lzycompute(LuceneRDDPartition.scala:34)
	at org.zouzias.spark.lucenerdd.partition.LuceneRDDPartition.indexWriter(LuceneRDDPartition.scala:34)
	at org.zouzias.spark.lucenerdd.partition.LuceneRDDPartition$$anonfun$3.apply(LuceneRDDPartition.scala:51)
	at org.zouzias.spark.lucenerdd.partition.LuceneRDDPartition$$anonfun$3.apply(LuceneRDDPartition.scala:48)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at org.zouzias.spark.lucenerdd.partition.LuceneRDDPartition.<init>(LuceneRDDPartition.scala:48)
	at org.zouzias.spark.lucenerdd.partition.LuceneRDDPartition$.apply(LuceneRDDPartition.scala:155)
	at org.zouzias.spark.lucenerdd.LuceneRDD$$anonfun$6.apply(LuceneRDD.scala:286)
	at org.zouzias.spark.lucenerdd.LuceneRDD$$anonfun$6.apply(LuceneRDD.scala:286)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by zouzias** [comment]
Hey, is it possible to upgrade to Spark 1.6.3 ? Also are you importing lucene in your project as well?

I see `org.apache.lucene.codecs.lucene41.Lucene41Codec$1.<init>(Lucene41Codec.java:59)` version 4.1.X here, but LuceneRDD uses 5.3.x. There might be issues with Lucene conflicting versions.

**Comment by SwathiTallapalli** [comment]
We cannot upgrade spark version because production server has 1.6.2.
But you are correct ,it is Lucene version issue. I tried with Lucene 5.3.2 version jar . It is running fine now.
Thanks again, it helped me alot

**Comment by zouzias** [comment]
Glad to hear that it works now!
